name: Trigger Vercel Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Deploy Request to Vercel
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
